POST https://accounts.spotify.com/api/token 
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=8b39e56d4dad491aaa626b87f7260358&client_secret=4f3e9a298b084c35846c5ddf5fc3927e

###
GET https://api.spotify.com/v1/search?q=&type=artist
Authorization: Bearer BQBu0k_q6DwHAvP4sRnDbiv8mcw9aRvZkIOW0hPVxPI4c7ialoC26qukcawqoKI9uyslAT8jtRuDUOiKzKegEvleBX2YFs9oU8CMijjeFLZKHGwGFjI

###
GET https://api.spotify.com/v1/artists/5l4nhyz8876RhgE2d18h65/albums
Authorization: Bearer BQC3jTVppnXUDqHGhM7Z_shCJt1DnNMt94b3GNr1zVSNX_qEtC0FEPeoD_Gxz7vm6ngafQl6pUCiIScO0TMyd30ic7tzBFlxek28BwlN4S8-YHdx6jQ

###
GET https://api.spotify.com/v1/albums/4aawyAB9vmqN3uQ7FjRGTy
Authorization: Bearer BQDz8gGhcMbYxhISA7tVhev_fx75b1Aj32S9cNMvkjjQyObGPIJq2yAVAt9gHjIYor90upZ2H9XeT9aBJFz2zSs-lw4leYwCKL5uopA35-qnxgQnygM